default: &default
  adapter: postgresql
  username: postgres
  password: 123
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost

development:
  <<: *default

  database: ylosix_development

test:
  <<: *default
  database: ylosix_test

# Do not keep production credentials in the repository,
# instead read the configuration from the environment.
#
# Example:
#   sqlite3://myuser:mypass@localhost/full/path/to/somedatabase
#
production:
  url: <%= ENV["DATABASE_URL"] %>
